version: "2"
services:
  nginx:
    image: seogwoojin1/springboot-nginx:0.1
    ports:
      - 80:80
    depends_on:
      - springboot-app
    networks:
      - mynetwork
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot

  springboot-app:
    image: seogwoojin1/demo-docker-springboot:0.1  # 올바른 이미지 이름을 사용합니다.
    container_name: demo-docker-springboot
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
    expose:
      - 8080
    networks:
      - mynetwork

networks:
  mynetwork: