version: '2'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    container_name: app
    depends_on:
      - db

  db:
    image: 'postgres:13.1-alpine'
    container_name: "db"
    environment:
      POSTGRES_DB: test1
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test