version: "2"
services:
  nginx:
    image: springboot-nginx:0.1
    ports:
      - 80:80
    depends_on:
      - springboot-app
    networks:
      - mynetwork

  springboot-app:
    image: demo-docker-springboot  # 올바른 이미지 이름을 사용합니다.
    container_name: demo-docker-springboot
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
    expose:
      - 8080
    networks:
      - mynetwork

networks:
  mynetwork: