name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set up environment variables
      run: |
        echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> $GITHUB_ENV
        echo "DATABASE_USER=${{ secrets.DATABASE_USER }}" >> $GITHUB_ENV
        echo "DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}" >> $GITHUB_ENV

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      run: ./gradlew build -x test

    - name: Build and push springboot-nginx image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/springboot-nginx:0.1 --file ./nginx/nginx_Dockerfile ./nginx
        docker push ${{ secrets.DOCKER_USERNAME }}/springboot-nginx:0.1

    - name: Build and push demo-docker-springboot image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/demo-docker-springboot:0.1 .
        docker push ${{ secrets.DOCKER_USERNAME }}/demo-docker-springboot:0.1

    - name: Run scripts on server
      uses: appleboy/ssh-action@master
      with:
        key: ${{ secrets.EC2_SSH_KEY }}
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        script: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/springboot-nginx:0.1
          docker pull ${{ secrets.DOCKER_USERNAME }}/demo-docker-springboot:0.1
          
          docker-compose down
          docker container prune -f
          docker-compose up -d
